# Jaisel Rahman <jaiselrahman@gmail.com>
# https://github.com/JaiselRahman/Flaminius2k19Web

FROM node:8-slim

ADD entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]